services:
  - type: web
    name: file-assist-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.FYP.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
